

spring:
  datasource:
    url: 
      jdbc:postgresql://beaveryfull.ckq7pjqco13u.us-east-1.rds.amazonaws.com:5432/postgres
    username: tatoelpato
    password: PaTe#7722
    dbcp2:
      driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties: 
      hibernate: 
        default_schema: public